feat: add `|||-` chomped text block syntax
google/jsonnet pull request #1175
Opened 2024-10-11 16:12 UTC by vergenzt

Resolves #289!

Was pretty easy to add as you can see. 🙂

Let me know if you have any concerns or feedback!

Only part I'm not sure of is the changes to [doc/third_party/MathJax-2.7.2/unpacked](https://github.com/google/jsonnet/compare/master...vergenzt:vergenzt%2Fgh-289-text-block-chomp?body=&expand=1#diff-558e4aab873bdaac5dc5907b5de80ba0db1e18f053f079dd0024cdaf3d3ca6a5) -- it looks like like at https://github.com/google/jsonnet/blob/9952fc5143097706919e73d4dd94287247461f2e/doc/_layouts/base.html#L22 we link to the root "packed" version of `MathJax.js`, but I can't figure out to re-"pack" the unpacked code. 🤔 I'm also not sure how critical it is though. 🤷🏻‍♂️

2024-10-31 17:49 UTC, vergenzt commented
Any updates? Anybody willing to review this and weigh in?

2025-01-09 14:51 UTC, betabandido commented
Is there any estimate on when this will get merged (and released)?

2025-01-09 15:50 UTC, MrG9090 approved these changes

2025-01-19 21:51 UTC, johnbartholomew commented
Hi. Thanks for your contribution, and sorry for the delay in processing it!

2025-01-19 21:53 UTC, johnbartholomew requested changes
The MathJax change is not needed - that operator list is nothing to do with jsonnet, so it shouldn't be updated for this change. As far as I can tell, those operators originate from the MathML spec - https://www.w3.org/TR/MathML/appendixc.html (the existing triple-pipe fence was added to the table in https://github.com/mathjax/MathJax/commit/bf862f6529b7edec47a1a244f8be9cb2366a7d22#diff-8e4e61c67ba8f00ac92875cb211f3a2ec8eef705f71d232d4d3dcb014d0517c0)

2025-01-20 19:25 UTC, merged

2025-03-28 20:40 UTC, vergenzt commented
> The MathJax change is not needed - that operator list is nothing to do with jsonnet, so it shouldn't be updated for this change. As far as I can tell, those operators originate from the MathML spec - https://www.w3.org/TR/MathML/appendixc.html (the existing triple-pipe fence was added to the table in [mathjax/MathJax@bf862f6#diff-8e4e61c67ba8f00ac92875cb211f3a2ec8eef705f71d232d4d3dcb014d0517c0](https://github.com/mathjax/MathJax/commit/bf862f6529b7edec47a1a244f8be9cb2366a7d22#diff-8e4e61c67ba8f00ac92875cb211f3a2ec8eef705f71d232d4d3dcb014d0517c0))

Yay thank you!!!