Load py_runtime/py_runtime_pair from rules_python
google/jsonnet pull request #1189
Opened 2024-12-09 22:44 UTC by mortenmj

2025-01-07 21:20 UTC, michaelschuett-tomtom commented
Hey, I just ran into this one as well. Would be awesome to get this landed as it looks to be blocking me from moving to bazel 8.x because of being pulled in by https://github.com/bazel-contrib/rules_jsonnet/tree/master. Although possibly that repo should actually change something so that BUILD files in this repo don't matter.

2025-01-13 11:29 UTC, johnbartholomew requested changes
In `platform_defs/BUILD`, the `default_python3_toolchain` target, the `toolchain_type` 
 property should also change to the one in python_rules:

```
toolchain(
    name = "default_python3_toolchain",
    toolchain = ":just_python3",
    toolchain_type = "@rules_python//python:toolchain_type",
)
```

2025-01-13 11:32 UTC, johnbartholomew commented
Thanks for the fix!

2025-01-15 06:04 UTC, deblasis commented
@mortenmj thanks for the fix, I guess you just need to update this:

[`master...deblasis:jsonnet:master`#diff-8db7ed2f5e](https://github.com/google/jsonnet/compare/master...deblasis:jsonnet:master#diff-8db7ed2f5ee51e0130bd9b00c97130b8b5ed3d263797941772b7e8fad163e0ebR19)

![image](https://github.com/user-attachments/assets/cd66e963-778d-42c6-b384-5dc7ac669811)

2025-01-17 10:48 UTC, johnbartholomew commented
I've added a commit to use `toolchain_type = "@rules_python//python:toolchain_type",`. Unfortunately there is another failure showing in the CI build-and-test-using-Bazel action. It looks like WORKSPACE refers to quite an old rules_jsonnet, and this probably also needs to be updated, though it may only be breaking our ability to run Jsonnet's own test suite with Bazel.

I'll look into it some more hopefully later today or early next week.

2025-01-18 14:01 UTC, merged

2025-01-18 18:53 UTC, simonff commented
Thank you for the fix. I'm still getting the error below in a rule using jsonnet. Repro:

git clone https://github.com/google/earthengine-catalog
cd earthengine-catalog
bazel test --define jsonnet_port=cpp //...

***
ERROR: Traceback (most recent call last):
	File "...bazel_simonf/be0a056b459fb929c3961680f76bd588/external/jsonnet+/platform_defs/BUILD", line 10, column 16, in <toplevel>
		py_runtime_pair(
	File "..._bazel_simonf/be0a056b459fb929c3961680f76bd588/external/bazel_tools/tools/python/toolchain.bzl", line 17, column 9, in py_runtime_pair
		fail("@bazel_tools//toolchain.bzl py_runtime_pair is deprecated. Use version from rules_python")
Error in fail: @bazel_tools//toolchain.bzl py_runtime_pair is deprecated. Use version from rules_python
ERROR: /tmp/earthengine-catalog/checker/tree/BUILD:44:8: While resolving toolchains for target //checker/tree:url_id_test (edcaa02): invalid registered toolchain '//platform_defs:default_python3_toolchain': no such target '@@jsonnet+//platform_defs:default_python3_toolchain': target 'default_python3_toolchain' not declared in package 'platform_defs' defined by ..._bazel_simonf/be0a056b459fb929c3961680f76bd588/external/jsonnet+/platform_defs/BUILD

2025-01-19 00:13 UTC, johnbartholomew commented
> I'm still getting the error below in a rule using jsonnet.

There hasn't been a new jsonnet release yet, nor a new rules_jsonnet bazel module release; I would expect both are needed. I intend to make a new jsonnet release soon, but usually the jsonnet and go-jsonnet releases are coordinated so there is some extra work for me to do there. And then rules_jsonnet probably needs a new release as well (I'm not a maintainer for rules_jsonnet).

If you want to get things working for now without waiting for a release, you can use [`git_override`](https://bazel.build/rules/lib/globals/module#git_override) in the earthengine-catalog `MODULE.bazel` to use the latest unreleased jsonnet as source, overriding the version rules_jsonnet points to. Add this at the start of `MODULE.bazel`:

```
# https://bazel.build/rules/lib/globals/module#git_override
git_override(
	module_name = "jsonnet",
	commit = "4487bfb8ba7ed7a3d91d79d4a1aa2205e7839558",
	remote = "https://github.com/google/jsonnet.git",
)
```

2025-01-19 16:46 UTC, simonff commented
Thank you, that works. Do you have an ETA for rolling out the fix officially as you described?